//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.22 at 12:35:14 AM CEST 
//

@XmlSchema(
	namespace = "http://sne.uva.nl/daci/1.0/schema", 
	elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
	xmlns = {
			@XmlNs(prefix = "daci", namespaceURI="http://sne.uva.nl/daci/1.0/schema"),
			@XmlNs(prefix = "ds", namespaceURI="http://www.w3.org/2000/09/xmldsig#")
	}
)

package nl.uva.sne.daci._1_0.schema;

import javax.xml.bind.annotation.*;
